repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^lambdas/

